import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2.112.2";
const url=Deno.env.get("SUPABASE_URL")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const out=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"content-type":"application/json","cache-control":"no-store"}});
function claims(jwt:string){try{let s=jwt.split('.')[1].replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return JSON.parse(atob(s))}catch{return {}}}
async function requireOwner(req:Request){const jwt=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!jwt)throw new Error("Authentication required");if(claims(jwt).aal!=="aal2")throw new Error("MFA verification required. Complete two-factor authentication before using the Platform Owner Console.");const{data,error}=await admin.auth.getUser(jwt);if(error||!data.user)throw new Error("Authentication required");const gate=await admin.rpc("operator_service_dashboard",{p_actor_user_id:data.user.id});if(gate.error)throw new Error("Platform Owner access required");return{user:data.user,dashboard:gate.data,jwt}}
const id=(v:unknown)=>{const s=String(v||"");if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s))throw new Error("Invalid ID");return s},ids=(v:unknown)=>Array.isArray(v)?v.map(id):[];
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const auth=await requireOwner(req),user=auth.user,b=await req.json().catch(()=>({})),action=String(b.action||"home");
if(action==="home")return out({ok:true,owner_email:user.email,dashboard:auth.dashboard});
if(action==="platform_releases"){const{data,error}=await admin.rpc("operator_service_platform_releases",{p_actor_user_id:user.id});if(error)throw error;return out({ok:true,releases:data})}
if(action==="create_platform_release"){const{data,error}=await admin.rpc("operator_service_create_platform_release",{p_actor_user_id:user.id,p_version_code:String(b.version_code||""),p_minimum_schema_version:String(b.minimum_schema_version||""),p_release_notes:String(b.release_notes||""),p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,release:data})}
if(action==="validate_platform_release"){const{data,error}=await admin.rpc("operator_service_validate_platform_release",{p_actor_user_id:user.id,p_release_id:id(b.release_id),p_source_commit_sha:String(b.source_commit_sha||""),p_automated_tests_passed:!!b.automated_tests_passed,p_security_review_passed:!!b.security_review_passed,p_acceptance_test_passed:!!b.acceptance_test_passed,p_notes:String(b.notes||""),p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,validation:data})}
if(action==="approve_platform_release"){const{data,error}=await admin.rpc("operator_service_approve_platform_release",{p_actor_user_id:user.id,p_release_id:id(b.release_id),p_reason:String(b.reason||""),p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,release:data})}
if(action==="schedule_platform_release"){const{data,error}=await admin.rpc("operator_service_schedule_platform_release",{p_actor_user_id:user.id,p_release_id:id(b.release_id),p_company_ids:ids(b.company_ids),p_rollout_stage:String(b.rollout_stage||"selected"),p_reason:String(b.reason||""),p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,rollout:data})}
if(action==="activate_platform_release"){const{data,error}=await admin.rpc("operator_service_activate_platform_release",{p_actor_user_id:user.id,p_release_id:id(b.release_id),p_company_ids:ids(b.company_ids),p_reason:String(b.reason||""),p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,rollout:data})}
if(action==="rollback_platform_release"){const{data,error}=await admin.rpc("operator_service_rollback_platform_release",{p_actor_user_id:user.id,p_release_id:id(b.release_id),p_company_ids:ids(b.company_ids),p_reason:String(b.reason||""),p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,rollout:data})}
if(action==="template_catalog"){const{data:templates,error}=await admin.from("industry_templates").select("id,template_code,name,description,status,is_blank_standard,created_at,updated_at").order("template_code");if(error)throw error;const{data:versions,error:ve}=await admin.from("industry_template_versions").select("id,industry_template_id,version_code,schema_version,status,minimum_client_version,published_at,created_at").order("created_at",{ascending:false});if(ve)throw ve;return out({ok:true,templates:templates||[],versions:versions||[]})}
if(action==="create_industry_template"){const{data,error}=await admin.rpc("operator_service_create_industry_template",{p_actor_user_id:user.id,p_template_code:String(b.template_code||""),p_name:String(b.name||""),p_description:String(b.description||""),p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,template:data})}
if(action==="create_template_version"){let config=b.configuration;if(typeof config==="string")config=JSON.parse(config);const{data,error}=await admin.rpc("operator_service_create_template_version",{p_actor_user_id:user.id,p_template_id:id(b.template_id),p_version_code:String(b.version_code||""),p_schema_version:String(b.schema_version||"1.0.1"),p_configuration:config,p_minimum_client_version:String(b.minimum_client_version||"1.0.1"),p_publish:!!b.publish,p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,template_version:data})}
if(action==="provision_customer_v2"){const{data,error}=await admin.rpc("operator_service_provision_customer_v2",{p_actor_user_id:user.id,p_name:String(b.name||""),p_slug:String(b.slug||""),p_timezone:String(b.timezone||"America/Boise"),p_owner_email:String(b.owner_email||""),p_plan_code:String(b.plan_code||"standard"),p_provisioning_key:String(b.provisioning_key||crypto.randomUUID()),p_trial_days:Number(b.trial_days||30),p_template_code:String(b.template_code||"BLANK"),p_template_version_code:b.template_version_code?String(b.template_version_code):null,p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,customer:data})}
const company=id(b.company_id);
if(action==="status"){const{data:cfg,error}=await admin.rpc("operator_service_customer_configuration",{p_actor_user_id:user.id,p_company_id:company});if(error)throw error;const{data:versions,error:ve}=await admin.from("configuration_versions").select("id,version_label,status,published_at,created_at").eq("company_id",company).order("created_at",{ascending:false});if(ve)throw ve;const{data:invites,error:ie}=await admin.rpc("operator_service_list_access_invites",{p_actor_user_id:user.id,p_company_id:company});if(ie)throw ie;return out({ok:true,configuration:cfg,rollback_candidates:(versions||[]).filter((v:any)=>v.status==="retired"&&v.published_at),invites:invites||[]})}
if(action==="list_access_invites"){const{data,error}=await admin.rpc("operator_service_list_access_invites",{p_actor_user_id:user.id,p_company_id:company});if(error)throw error;return out({ok:true,invites:data||[]})}
if(action==="create_access_invite"){const role=String(b.role||"");const allowed=new Set(["manager","market_leader","area_leader","executive","viewer"]);if(!allowed.has(role))throw new Error("Unsupported invited role");const{data,error}=await admin.rpc("operator_service_create_access_invite",{p_actor_user_id:user.id,p_company_id:company,p_email:String(b.email||""),p_role:role,p_location_ids:ids(b.location_ids),p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,invite:data})}
if(action==="revoke_access_invite"){const{data,error}=await admin.rpc("operator_service_revoke_access_invite",{p_actor_user_id:user.id,p_company_id:company,p_invite_id:id(b.invite_id),p_reason:String(b.reason||"Revoked by CTOD Platform Owner"),p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,result:data})}
if(action==="send_access_invite"){const inviteId=id(b.invite_id);const r=await fetch(url+"/functions/v1/ctod-send-customer-invite",{method:"POST",headers:{authorization:"Bearer "+auth.jwt,apikey:service,"content-type":"application/json"},body:JSON.stringify({invite_id:inviteId})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||"Invite delivery failed");return out({ok:true,delivery:d.delivery,email:d.email})}
if(action==="begin_customer_sandbox"){const{data,error}=await admin.rpc("operator_service_begin_configuration_draft",{p_actor_user_id:user.id,p_company_id:company,p_version_label:String(b.version_label||"")||null,p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,configuration:data})}
if(action==="mutate_customer_configuration"){const{data,error}=await admin.rpc("operator_service_mutate_configuration",{p_actor_user_id:user.id,p_company_id:company,p_operation:String(b.operation||""),p_payload:b.configuration_payload||{},p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,configuration:data})}
if(action==="validate"){const{data,error}=await admin.rpc("operator_service_validate_configuration",{p_actor_user_id:user.id,p_company_id:company,p_config_version_id:id(b.config_version_id),p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,validation:data})}
if(action==="promote"){const{data,error}=await admin.rpc("operator_service_promote_configuration",{p_actor_user_id:user.id,p_company_id:company,p_config_version_id:id(b.config_version_id),p_reason:String(b.reason||""),p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,configuration:data})}
if(action==="discard_draft"){const{data,error}=await admin.rpc("operator_service_discard_configuration_draft",{p_actor_user_id:user.id,p_company_id:company,p_reason:String(b.reason||"Discard draft"),p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,configuration:data})}
if(action==="rollback"){const{data,error}=await admin.rpc("operator_service_rollback_configuration",{p_actor_user_id:user.id,p_company_id:company,p_target_config_version_id:id(b.target_config_version_id),p_reason:String(b.reason||""),p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,configuration:data})}
return out({ok:false,error:"Unknown action"},404)}catch(e){return out({ok:false,error:e instanceof Error?e.message:String(e)},400)}});