import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2.112.2";
const url=Deno.env.get("SUPABASE_URL")!;
const service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const out=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"content-type":"application/json","cache-control":"no-store"}});
async function requireOwner(req:Request){const jwt=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!jwt)throw new Error("Authentication required");const{data,error}=await admin.auth.getUser(jwt);if(error||!data.user)throw new Error("Authentication required");const{data:op,error:oe}=await admin.schema("private").from("platform_operators").select("user_id,operator_role,active,display_name").eq("user_id",data.user.id).eq("active",true).maybeSingle();if(oe||!op||op.operator_role!=="platform_admin")throw new Error("Platform Owner access required");return data.user;}
const id=(v:unknown)=>{const s=String(v||"");if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s))throw new Error("Invalid ID");return s};
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const user=await requireOwner(req);const b=await req.json().catch(()=>({}));const action=String(b.action||"home");
if(action==="home"){const{data,error}=await admin.rpc("operator_service_dashboard",{p_actor_user_id:user.id});if(error)throw error;return out({ok:true,owner_email:user.email,dashboard:data});}
if(action==="platform_releases"){const{data,error}=await admin.rpc("operator_service_platform_releases",{p_actor_user_id:user.id});if(error)throw error;return out({ok:true,releases:data});}
if(action==="template_catalog"){const{data:templates,error}=await admin.from("industry_templates").select("id,template_code,name,description,status,is_blank_standard,created_at,updated_at").order("template_code");if(error)throw error;const{data:versions,error:ve}=await admin.from("industry_template_versions").select("id,industry_template_id,version_code,schema_version,status,minimum_client_version,published_at,created_at").order("created_at",{ascending:false});if(ve)throw ve;return out({ok:true,templates:templates||[],versions:versions||[]});}
if(action==="create_industry_template"){const{data,error}=await admin.rpc("operator_service_create_industry_template",{p_actor_user_id:user.id,p_template_code:String(b.template_code||""),p_name:String(b.name||""),p_description:String(b.description||""),p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,template:data});}
if(action==="create_template_version"){let config=b.configuration;if(typeof config==="string")config=JSON.parse(config);const{data,error}=await admin.rpc("operator_service_create_template_version",{p_actor_user_id:user.id,p_template_id:id(b.template_id),p_version_code:String(b.version_code||""),p_schema_version:String(b.schema_version||"1.0.1"),p_configuration:config,p_minimum_client_version:String(b.minimum_client_version||"1.0.1"),p_publish:!!b.publish,p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,template_version:data});}
if(action==="provision_customer_v2"){const name=String(b.name||"").trim(),slug=String(b.slug||"").trim(),template=String(b.template_code||"BLANK").trim();if(!name||!slug)throw new Error("Company name and slug are required");const{data,error}=await admin.rpc("operator_service_provision_customer_v2",{p_actor_user_id:user.id,p_name:name,p_slug:slug,p_timezone:String(b.timezone||"America/Boise"),p_owner_email:String(b.owner_email||""),p_plan_code:String(b.plan_code||"standard"),p_provisioning_key:String(b.provisioning_key||crypto.randomUUID()),p_trial_days:Number(b.trial_days||30),p_template_code:template,p_template_version_code:b.template_version_code?String(b.template_version_code):null,p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,customer:data});}
const company=id(b.company_id);
if(action==="status"){const{data:cfg,error}=await admin.rpc("operator_service_customer_configuration",{p_actor_user_id:user.id,p_company_id:company});if(error)throw error;const{data:versions,error:ve}=await admin.from("configuration_versions").select("id,version_label,status,published_at,created_at").eq("company_id",company).order("created_at",{ascending:false});if(ve)throw ve;const{data:validations,error:vle}=await admin.schema("private").from("customer_configuration_validations").select("id,config_version_id,passed,checks,checksum,created_at").eq("company_id",company).order("created_at",{ascending:false}).limit(10);if(vle)throw vle;const{data:history,error:he}=await admin.schema("private").from("customer_configuration_release_history").select("id,from_config_version_id,to_config_version_id,action,reason,created_at").eq("company_id",company).order("created_at",{ascending:false}).limit(20);if(he)throw he;return out({ok:true,configuration:cfg,validations:validations||[],release_history:history||[],rollback_candidates:(versions||[]).filter((v:any)=>v.status==="retired"&&v.published_at)});}
if(action==="begin_customer_sandbox"){const{data,error}=await admin.rpc("operator_service_begin_configuration_draft",{p_actor_user_id:user.id,p_company_id:company,p_version_label:String(b.version_label||"").trim()||null,p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,configuration:data});}
if(action==="mutate_customer_configuration"){const operation=String(b.operation||"").trim();if(!operation)throw new Error("Configuration operation is required");const payload=b.configuration_payload&&typeof b.configuration_payload==="object"?b.configuration_payload:{};const{data,error}=await admin.rpc("operator_service_mutate_configuration",{p_actor_user_id:user.id,p_company_id:company,p_operation:operation,p_payload:payload,p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,configuration:data});}
if(action==="validate"){const{data,error}=await admin.rpc("operator_service_validate_configuration",{p_actor_user_id:user.id,p_company_id:company,p_config_version_id:id(b.config_version_id),p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,validation:data});}
if(action==="promote"){const reason=String(b.reason||"").trim();if(!reason)throw new Error("Promotion reason is required");const{data,error}=await admin.rpc("operator_service_promote_configuration",{p_actor_user_id:user.id,p_company_id:company,p_config_version_id:id(b.config_version_id),p_reason:reason,p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,configuration:data});}
if(action==="discard_draft"){const reason=String(b.reason||"Discard customer sandbox draft").trim();const{data,error}=await admin.rpc("operator_service_discard_configuration_draft",{p_actor_user_id:user.id,p_company_id:company,p_reason:reason,p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,configuration:data});}
if(action==="rollback"){const reason=String(b.reason||"").trim();if(!reason)throw new Error("Rollback reason is required");const{data,error}=await admin.rpc("operator_service_rollback_configuration",{p_actor_user_id:user.id,p_company_id:company,p_target_config_version_id:id(b.target_config_version_id),p_reason:reason,p_request_id:crypto.randomUUID()});if(error)throw error;return out({ok:true,configuration:data});}
return out({ok:false,error:"Unknown action"},404);}catch(e){return out({ok:false,error:e instanceof Error?e.message:String(e)},400);}});
