-- Ensure finalized/two-page summary payload contains all locked 001 talent intelligence.
-- Historical fields remain preserved; active payload exposes the current contract.
create or replace function public.get_review_form(p_review_id uuid)
returns jsonb language plpgsql stable set search_path='public' as $function$
declare r public.reviews; outj jsonb;
begin
 select * into r from reviews where id=p_review_id; if not found then raise exception 'Review not found'; end if; if not private.can_access_location(r.company_id,r.location_id) then raise exception 'Access denied'; end if;
 select jsonb_build_object(
 'review',jsonb_build_object('id',r.id,'status',r.status,'review_date',r.review_date,'scheduled_review_date',r.scheduled_review_date,'next_review_date',r.next_review_date,'overall_rating_label',r.overall_rating_label,'overall_score',r.overall_score,'overall_percent',r.overall_percent),
 'employee',(select jsonb_build_object('id',e.id,'employee_code',e.employee_code,'name',e.first_name||' '||e.last_name,'role',ro.title,'location',l.name,'location_code',l.location_code) from employees e join roles ro on ro.id=r.role_id join locations l on l.id=r.location_id where e.id=r.employee_id),
 'ratings',(select coalesce(jsonb_agg(jsonb_build_object('id',x.id,'code',x.code,'label',x.label,'score',x.score_value) order by x.sort_order),'[]'::jsonb) from rating_scale_items x where x.config_version_id=r.config_version_id and x.employee_visible),
 'reasons',(select coalesce(jsonb_agg(jsonb_build_object('id',rd.id,'label',rd.label,'rating_code',rd.rating_code,'category',rd.category,'role_id',rd.role_id,'question_id',rd.question_id) order by rd.sort_order),'[]'::jsonb) from reason_definitions rd where rd.config_version_id=r.config_version_id and rd.active and rd.question_id in (select q.id from question_definitions q where q.config_version_id=r.config_version_id and q.active and (q.role_id is null or q.role_id=r.role_id)) and rd.reason_type in ('review_org','review_role')),
 'questions',(select coalesce(jsonb_agg(jsonb_build_object('id',q.id,'code',q.question_code,'section',q.section_name,'section_code',q.section_code,'text',q.question_text,'category',q.question_code,'display_category',q.category,'sort_order',q.sort_order,'requires_rating',q.requires_rating,'requires_reason',q.requires_reason,'answer',case when a.id is null then null else jsonb_build_object('id',a.id,'rating_id',a.rating_id,'primary_reason_id',a.primary_reason_id,'additional_reason_id',a.additional_reason_id,'manager_note',a.manager_note,'confirmed',a.confirmed_current_cycle) end) order by q.section_code,q.sort_order),'[]'::jsonb) from question_definitions q left join review_answers a on a.review_id=r.id and a.question_id=q.id where q.config_version_id=r.config_version_id and q.active and (q.role_id is null or q.role_id=r.role_id)),
 'goals',(select coalesce(jsonb_agg(jsonb_build_object('id',g.id,'goal_text',g.goal_text,'goal_type',g.goal_type,'status',g.status,'target_date',g.target_date,'raise_linked',g.raise_linked,'promotion_linked',g.promotion_linked) order by g.created_at),'[]'::jsonb) from goals g where g.employee_id=r.employee_id and g.status in ('not_started','in_progress') and private.can_access_employee(g.company_id,g.employee_id)),
 'career',(select jsonb_build_object('promotion_interest',cd.promotion_interest,'desired_role_id',cd.desired_role_id,'desired_role',dr.title,'final_desired_role_id',cd.final_desired_role_id,'final_desired_role',fr.title,'career_direction',cd.career_direction,'career_direction_reason',cd.career_direction_reason,'promotion_readiness',cd.promotion_readiness,'next_year_goal',cd.next_year_goal,'specialist_growth_path',cd.specialist_growth_path,'safety_priority_response',cd.safety_priority_response,'career_feeling_response',cd.career_feeling_response,'work_preference_response',cd.work_preference_response,'relocation_openness_response',cd.relocation_openness_response) from career_decisions cd left join roles dr on dr.id=cd.desired_role_id left join roles fr on fr.id=cd.final_desired_role_id where cd.review_id=r.id limit 1),
 'compensation',(select to_jsonb(cc) from compensation_decisions cc where cc.review_id=r.id limit 1),
 'summary',(select jsonb_build_object('employee_comments',s.employee_comments,'manager_summary',s.manager_summary) from review_summaries s where s.review_id=r.id)
 ) into outj; return outj;
end $function$;